package cn.demo.order.mapper;

import cn.demo.order.model.entity.demoOrderEntityExample;
import cn.demo.order.model.entity.demoOrderEntity;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface demoOrderEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_order
     *
     * @mbg.generated
     */
    long countByExample(demoOrderEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_order
     *
     * @mbg.generated
     */
    int insert(demoOrderEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_order
     *
     * @mbg.generated
     */
    int insertSelective(@Param("record") demoOrderEntity record, @Param("selective") demoOrderEntity.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_order
     *
     * @mbg.generated
     */
    demoOrderEntity selectOneByExample(demoOrderEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_order
     *
     * @mbg.generated
     */
    demoOrderEntity selectOneByExampleSelective(@Param("example") demoOrderEntityExample example, @Param("selective") demoOrderEntity.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_order
     *
     * @mbg.generated
     */
    List<demoOrderEntity> selectByExampleSelective(@Param("example") demoOrderEntityExample example, @Param("selective") demoOrderEntity.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_order
     *
     * @mbg.generated
     */
    List<demoOrderEntity> selectByExample(demoOrderEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_order
     *
     * @mbg.generated
     */
    demoOrderEntity selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") demoOrderEntity.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_order
     *
     * @mbg.generated
     */
    demoOrderEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") demoOrderEntity record, @Param("example") demoOrderEntityExample example, @Param("selective") demoOrderEntity.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") demoOrderEntity record, @Param("example") demoOrderEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(@Param("record") demoOrderEntity record, @Param("selective") demoOrderEntity.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(demoOrderEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_order
     *
     * @mbg.generated
     */
    int batchInsert(@Param("list") List<demoOrderEntity> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_order
     *
     * @mbg.generated
     */
    int batchInsertSelective(@Param("list") List<demoOrderEntity> list, @Param("selective") demoOrderEntity.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_order
     *
     * @mbg.generated
     */
    int upsert(demoOrderEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_order
     *
     * @mbg.generated
     */
    int upsertSelective(@Param("record") demoOrderEntity record, @Param("selective") demoOrderEntity.Column ... selective);
}