package cn.demo.order.feign.api.mapper;

import cn.demo.order.feign.api.entity.OrderEntity;
import cn.demo.order.feign.api.entity.OrderEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_order
     *
     * @mbg.generated
     */
    long countByExample(OrderEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_order
     *
     * @mbg.generated
     */
    int insert(OrderEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_order
     *
     * @mbg.generated
     */
    int insertSelective(@Param("record") OrderEntity record, @Param("selective") OrderEntity.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_order
     *
     * @mbg.generated
     */
    OrderEntity selectOneByExample(OrderEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_order
     *
     * @mbg.generated
     */
    OrderEntity selectOneByExampleSelective(@Param("example") OrderEntityExample example, @Param("selective") OrderEntity.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_order
     *
     * @mbg.generated
     */
    List<OrderEntity> selectByExampleSelective(@Param("example") OrderEntityExample example, @Param("selective") OrderEntity.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_order
     *
     * @mbg.generated
     */
    List<OrderEntity> selectByExample(OrderEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_order
     *
     * @mbg.generated
     */
    OrderEntity selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") OrderEntity.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_order
     *
     * @mbg.generated
     */
    OrderEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") OrderEntity record, @Param("example") OrderEntityExample example, @Param("selective") OrderEntity.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") OrderEntity record, @Param("example") OrderEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(@Param("record") OrderEntity record, @Param("selective") OrderEntity.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OrderEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_order
     *
     * @mbg.generated
     */
    int batchInsert(@Param("list") List<OrderEntity> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_order
     *
     * @mbg.generated
     */
    int batchInsertSelective(@Param("list") List<OrderEntity> list, @Param("selective") OrderEntity.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_order
     *
     * @mbg.generated
     */
    int upsert(OrderEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_order
     *
     * @mbg.generated
     */
    int upsertSelective(@Param("record") OrderEntity record, @Param("selective") OrderEntity.Column ... selective);
}