version: "3.7"
services:
  db:
    image: mysql:8.0.18
    container_name: server_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "mrMGB7fbDkZ9I5Pp"
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - mysql_db:/var/lib/mysql
volumes:
  mysql_db:g