server:
  port: 58889
spring:
  application:
    name: demo-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 47.111.244.5:8848
        namespace: 82632dc2-fce3-4288-b49e-9d270643df74
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
      filter:
        enabled: false
      #限流操作
      scg:
        fallback:
          mode: response
          response-status: 455
          response-body: error!
      #nacos配置动态限流规则
#      datasource:
#        ds:
#          nacos:
#            server-addr: ${spring.cloud.nacos.discovery.server-addr} #nacos地址
#            dataId: ${spring.application.name}-sentinel
#            groupId: SENTINEL-DATASOURCE
#            rule-type: flow
#            namespace: ${spring.cloud.nacos.discovery.namespace}
    gateway:
      httpclient:
        websocket:
          max-frame-payload-length: 655350
      discovery:
        locator:
          enabled: true
      routes:
        - id: storage
          uri: lb://demo-storage
          predicates: #决定了一个请求走哪一个路由
            - Path=/api/storage/**
            - Method=POST
          filters:
            - StripPrefix=1 #表示截取一级路径/api，从二级url路径转发,
        - id: clientTest
          uri: lb://demo-nacos-client
          predicates: #决定了一个请求走哪一个路由
            - Path=/api/test/**
          filters:
            - StripPrefix=1 #表示截取一级路径/api，从二级url路径转发,
