version: '3.1'

services:
  seata-server:
    image: seataio/seata-server:1.1.0
    container_name: seata-server
    restart: always
    ports:
      - "8091:8091"
    environment:
      # 设置为本地的内网ip
      - SEATA_IP=172.16.168.126
      - STORE_MODE=db
      - SEATA_CONFIG_NAME=file:/root/seata-config/registry

    volumes:
      - ./config:/root/seata-config
      - ./logs:/root/logs
