server:
  port: 40000
  servlet:
    # context-path: /order
    session:
      timeout: 2000s

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time: GMT+8
  application:
    name: demo-order
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://192.168.101.60:3306/demo_order?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
      username: cjl
      password: 'cjl1234'
      driver-class-name: com.mysql.jdbc.Driver
      # 初始化大小，最小，最大
      initialSize: 5
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  redis:
    database: 10
    host: 192.168.101.60
    port: 6379
    #password:
  redission-lock:
    enable: true
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.101.60:8848
        #namespace: 82632dc2-fce3-4288-b49e-9d270643df74
#    sentinel:
#      transport:
#        # 取消Sentinel控制台懒加载
#        eager: true
#        # sentinel控制台地址
#        dashboard: 192.168.101.60:8080
#      #nacos配置动态限流规则
#      datasource:
#        # 这边可以配置多个如ds1
#        ds:
#          nacos:
#            # nacos地址
#            server-addr: ${spring.cloud.nacos.discovery.server-addr}
#            dataId: ${spring.application.name}-sentinel
#            groupId: SENTINEL-DATASOURCE
#            # rule-type：表示数据源中规则属于哪种类型，如flow、degrade、param-flow、gw-flow等。
#            rule-type: flow
#            # namespace: ${spring.cloud.nacos.discovery.namespace}

# feign sentinel 是否开启
feign:
  sentinel:
    enabled: true

# nacos 配置中心
nacos:
  config:
    server-addr: 192.168.101.60:8848
    #namespace: xxx

seata:
  enabled: true
  tx-service-group: my_test_tx_group
  enable-auto-data-source-proxy: true
  application-id: ${spring.application.name}
  config:
    type: nacos
    nacos:
      group: SEATA_GROUP
      server-addr: 192.168.101.60:8848
      #namespace: 82632dc2-fce3-4288-b49e-9d270643df74
  registry:
    type: nacos
    nacos:
      cluster: default
      server-addr: 192.168.101.60:8848
      #namespace: 82632dc2-fce3-4288-b49e-9d270643df74

mybatis:
  typeAliasesPackage: cn.demoorigin.order.model.entity
  mapperLocations: classpath:/mapper/**/*.xml

# 分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

swagger:
  enabled: false
  base-path: /**
  base-package: 'cn.demo.micro.market.frontend'
  title: '行情API'
  description: '基于Swagger构建的SpringBoot RESTApi 文档'
  version: '1.0.0'
  swagger.contact.email: 'demo@demo.cn'
