version: '3.1'

services:
  seata-server:
    image: seataio/seata-server:1.3.0
    container_name: seata-server
    restart: always
    ports:
      - "8091:8091"
    environment:
      # 设置为本地的内网ip,可以通过ifconfig命令查看(docker部署不要用127.0.0.1)
      - SEATA_IP=192.168.101.60
      - STORE_MODE=db
      - SEATA_CONFIG_NAME=file:/root/seata-config/registry

    volumes:
      - ./config:/root/seata-config
      - ./logs:/root/logs
