random: thOt2P7V8Z9uiEC04spxFQLtHVcPCErA
spring:
  messages:
    basename: file:/application/lottery/i18n/messages
    lgPath: /application/lottery/i18n
    encoding: UTF-8
    locale: zh_CN,en_US
    header: language
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

feign:
  client:
    config:
      default:
        connect-timeout: 10000
        read-timeout: 10000
  sentinel:
    enabled: true

mybatis-plus:
  mapper-locations: classpath*:xml/*.xml
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

feign-api:
  order:
    url: ''
  storage:
    url: ''